/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { TestContract } from "./TestContract";
export * as factories from "./factories";
export { ERC20__factory } from "./factories/ERC20__factory";
export { TestContract__factory } from "./factories/TestContract__factory";
