nodeLinker: node-modules

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${RAWR_MULTICALL_NPM_AUTH_TOKEN:-Please set your access token}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
