name: "Lint and typecheck"
on: [push]
  
jobs:
  lint-and-checktype:
    runs-on: ubuntu-latest

    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        cache: yarn

    - name: find yarn
      run: which yarn
      
    - name: Set yarn version to version 3.x
      run: yarn set version 3.3.1
    
    - name: Add yarn workspace-tool
      run: yarn plugin import workspace-tools
       
    - name: Run install
      run: yarn install --immutable

    - name: Run build
      run: yarn workspaces foreach run build

    - name: Lint 
      run: yarn workspaces foreach run lint:nofix
       
    - name: Type check
      run: yarn workspaces foreach run typecheck
